# Site settings
author: Dwayne McFarlane
title: The Long Journey Accelerated 
header-img: img/home-bg.png
email: dwaynemcfarlaneny@gmail.com
copyright_name: Dwayne McFarlane
description: > # this means to ignore newlines until "baseurl:"
  To code and conquer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dwaine18

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
